# For detailed descriptions, see the reference:
# https://supabase.com/docs/guides/cli/config

[api]
port = 54321
schemas = ["public", "storage"]

[db]
# Port to use for the database URL that is output when running `supabase start`.
# If this conflicts with your local database, you can set the `DB_URL` environment variable to override.
port = 54322

[studio]
port = 3000
api_url = "http://localhost"

[inbucket]
port = 54324

[analytics]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
jwt_expiry = 3600

[storage]
file_size_limit = "50MB"

[functions]
[functions.verify_jwt]
enabled = false
